[app_settings]
host = "0.0.0.0"
port = 8000
use_testcontainers = "True"

[db_settings]
name = "test_db"
user = "user"
password = "1234"
host = "localhost"
port = 5432
[scheduler]
refresh_interval = 30
