"""new service and user models

Revision ID: 7e8a423b2aeb
Revises: 001
Create Date: 2026-05-16 16:36:09.092378

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e8a423b2aeb"
down_revision: Union[str, Sequence[str], None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sla_breach", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_closed_at"), "incidents", ["closed_at"], unique=False)
    op.create_index(op.f("ix_incidents_service_id"), "incidents", ["service_id"], unique=False)
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("recipients", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_log_incident_id"), "notification_log", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_log_service_id"), "notification_log", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_check_results_checked_at"), "check_results", ["checked_at"], unique=False
    )
    op.add_column("services", sa.Column("sla_target_pct", sa.Float(), nullable=False))
    op.add_column("services", sa.Column("owner_emails", sa.JSON(), nullable=True))
    op.add_column("services", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("services", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f("ix_services_is_active"), "services", ["is_active"], unique=False)
    op.create_foreign_key(None, "services", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="foreignkey")
    op.drop_index(op.f("ix_services_is_active"), table_name="services")
    op.drop_column("services", "updated_at")
    op.drop_column("services", "created_by")
    op.drop_column("services", "owner_emails")
    op.drop_column("services", "sla_target_pct")
    op.drop_index(op.f("ix_check_results_checked_at"), table_name="check_results")
    op.drop_index(op.f("ix_notification_log_service_id"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_incident_id"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(op.f("ix_incidents_service_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_closed_at"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
