"""new service and user models

Revision ID: 7e8a423b2aeb
Revises: 001
Create Date: 2026-05-16 16:36:09.092378

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e8a423b2aeb"
down_revision: Union[str, Sequence[str], None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_check_results_checked_at"), "check_results", ["checked_at"], unique=False
    )
    op.add_column("services", sa.Column("sla_target_pct", sa.Float(), nullable=False))
    op.add_column("services", sa.Column("owner_emails", sa.JSON(), nullable=True))
    op.add_column("services", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("services", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f("ix_services_is_active"), "services", ["is_active"], unique=False)
    op.create_foreign_key(None, "services", "users", ["created_by"], ["id"])
    op.create_check_constraint("ck_services_interval_ms_min", "services", "interval_ms >= 1000")
    op.create_check_constraint(
        "ck_services_sla_range", "services", "sla_target_pct >= 0 AND sla_target_pct <= 100"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_services_sla_range", "services", type_="check")
    op.drop_constraint("ck_services_interval_ms_min", "services", type_="check")
    op.drop_constraint(None, "services", type_="foreignkey")
    op.drop_index(op.f("ix_services_is_active"), table_name="services")
    op.drop_column("services", "updated_at")
    op.drop_column("services", "created_by")
    op.drop_column("services", "owner_emails")
    op.drop_column("services", "sla_target_pct")
    op.drop_index(op.f("ix_check_results_checked_at"), table_name="check_results")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
